### ISSUE TITLE
unable to download using download_oasis_scans*.sh scripts

### ISSUE THREAD

**Issue by fangq** [NrgXnat/oasis-scripts#37] opened 2024-02-13 20:51 UTC
I am new to XNAT. I am trying to download the OASIS dataset from the scripts provided in this repo, but I got the following error
```
$ ./download_oasis_scans_bids.sh oasis_scan_download_example.csv orig username
Downloading all scans for OAS30001_MR_d0129.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0129/scans/ALL/files?format=tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0   1350      0 --:--:-- --:--:-- --:--:--  1354
Could not complete the scan download. Either could not find any scans for OAS30001_MR_d0129, or the download failed.
Done with OAS30001_MR_d0129.
```

the oasis_scan_download_example.csv was provided as the built-in example. 

I also tried downloading the experiment_ids using web-based xnat central for OASIS-1 and OASIS-2 datasets, but when downloading it using the bash scripts, all of them failed (I tried all downloa_oasis_scans* variants).

is this a known problem or I need to set up something first? thanks

**Comment by sarahkeefe** [comment] 2024-02-28 16:56
Hi, sorry for the delayed response. The download script should be asking you to enter your password when you run it. Are you using the correct username? If you let me know what it is I can confirm that you have access on Central. Another option to try is to log in to XNAT Central, ensure that you can access the OASIS-3 project, and then go to https://central.xnat.org/data/services/tokens/issue. Use the string next to "alias" in place of your username when running the script, and paste the string next to "secret" when it asks for your password. Let me know how it goes and I can assist further if this doesn't work.

The OASIS-1 and OASIS-2 data can be downloaded directly from oasis-brains.org and does not need to be downloaded via XNAT Central. If you go to the datasets section on oasis-brains.org you can click "Download Instructions" for each of those datasets and there will be a link to a compressed file of that dataset.

**Comment by fangq** [comment] 2024-02-28 20:33
@sarahkeefe, thanks for getting back to me.

I've already requested access for OASIS-3 on xnat central a few weeks ago, although I did not hear back, and wasn't sure if it is still being actively reviewed. I can try again. It seems that the error was likely because I do not have access - I did type in my username/password when running the script.

I am particularly interested in the BIDS formatted OASIS datasets. if I understood this correctly, the `download_oasis_scans_bids.sh` script was only designed to reformat OASIS-3/4, but not 1-2? is this correct?

**Comment by sarahkeefe** [comment] 2024-02-28 21:03
Ah ok, if you don't currently have access to the OASIS-3 project on XNAT Central (ie. you can see and access the OASIS3 data when you log in to XNAT Central) then you will need to follow up about your data use agreement and ensure you can get added to the XNAT Central project before you use the download scripts.

OASIS-1 and OASIS-2 are not available in BIDS format, only OASIS3.
I'm going to close this issue as completed since it sounds like it is an access issue and not script-related.

**Closed by sarahkeefe** 2024-02-28 21:03 UTC

**Comment by vijaypatidar123** [comment] 2025-10-30 21:20
I am new to XNAT. I am trying to download the OASIS-3 dataset from the scripts provided in this repo, but I got the following error

Enter your password for accessing OASIS data on NITRC IR:
Error starting session.  Maybe a bad username/password?

credentials are correct but don't know why I am getting this error 
please help me to find the solution

**Comment by sarahkeefe** [comment] 2025-10-30 21:26
Hi Vijay, this issue is closed. Please try resetting your password on NITRC and retry the script and you can open a new issue if that does not work. thanks!
